# Generated by Django 4.0.3 on 2022-06-05 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceDetected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gender', models.CharField(default='Male', max_length=6)),
                ('StartX', models.IntegerField()),
                ('EndX', models.IntegerField()),
                ('EndY', models.IntegerField()),
                ('Image', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='AppApi.uploadedimage')),
            ],
        ),
    ]
