# Generated by Django 4.0.3 on 2022-06-23 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppApi', '0003_facedetected_starty_alter_facedetected_endx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='Confidence',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='Gender',
            field=models.CharField(default='Male', max_length=6),
        ),
    ]
